"""Database creationn

Revision ID: 1a7ec1802f1e
Revises: 7d04614acbaa
Create Date: 2023-01-17 03:12:45.331500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7ec1802f1e'
down_revision = '7d04614acbaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
