"""Database creation2n

Revision ID: 87d801945aed
Revises: 8f23bef4c8f4
Create Date: 2023-01-17 03:48:37.566043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d801945aed'
down_revision = '8f23bef4c8f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('menu', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('menu', 'submenus_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu', 'dishes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'dishes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu', 'submenus_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('menu', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
