"""Database creation2n

Revision ID: 8f23bef4c8f4
Revises: 1a7ec1802f1e
Create Date: 2023-01-17 03:28:28.567337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f23bef4c8f4'
down_revision = '1a7ec1802f1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
