"""Database creation2n

Revision ID: bc87da391172
Revises: 7b2fcd99506d
Create Date: 2023-01-17 17:00:30.827600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc87da391172'
down_revision = '7b2fcd99506d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
