"""Database creation2n

Revision ID: c2cd833fedfa
Revises: 87d801945aed
Create Date: 2023-01-17 03:50:43.822657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cd833fedfa'
down_revision = '87d801945aed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('menu', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('menu', 'submenus_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu', 'dishes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'dishes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu', 'submenus_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('menu', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
