"""Database creation2n

Revision ID: c53502cc417f
Revises: e75eaccfdb29
Create Date: 2023-01-18 00:14:45.726208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53502cc417f'
down_revision = 'e75eaccfdb29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dish', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dish', 'price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dish', 'submenu_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('submenu', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('submenu', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('submenu', 'menu_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submenu', 'menu_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('submenu', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('submenu', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dish', 'submenu_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dish', 'price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dish', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dish', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
