"""Database creation2n

Revision ID: d4689d75e767
Revises: bc87da391172
Create Date: 2023-01-17 22:10:46.038052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4689d75e767'
down_revision = 'bc87da391172'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
