"""Database creation2n

Revision ID: da7a5352d1e3
Revises: 42449af57aa5
Create Date: 2023-01-18 02:12:52.114412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7a5352d1e3'
down_revision = '42449af57aa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'submenu_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'submenu_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
