"""Database creation2n

Revision ID: dd29701f922f
Revises: d4689d75e767
Create Date: 2023-01-17 22:20:39.891886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd29701f922f'
down_revision = 'd4689d75e767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
