"""Database creation2n

Revision ID: e75eaccfdb29
Revises: dd29701f922f
Create Date: 2023-01-17 22:34:25.825527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75eaccfdb29'
down_revision = 'dd29701f922f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
